(in-ns 'net.edmacdonald.pathfinder.entities)

(entity-type feat)

(def feats #{(feat "adopted ancestry")
             (feat "armor proficiency")
             (feat "breath control")
             (feat "canny acumen")
             (feat "diehard")
             (feat "fast recovery")
             (feat "feather step")
             (feat "fleet")
             (feat "incredible initiative")
             (feat "ride")
             (feat "shield block")
             (feat "toughness")
             (feat "weapon proficiency")
             (feat "ancestral paragon")
             (feat "untrained improvisation")
             (feat "expeditious search")
             (feat "incredible investiture")
             (feat "assurance")
             (feat "dubious knowledge")
             (feat "quick identification")
             (feat "recognize spell")
             (feat "skill training")
             (feat "trick magic item")
             (feat "automatic knowledge")
             (feat "magical shorthand")
             (feat "quick recognition")
             (feat "cat fall")
             (feat "quick squeeze")
             (feat "steady balance")
             (feat "nimble crawl")
             (feat "kip up")
             (feat "arcane sense")
             (feat "unified theory")
             (feat "combat climber")
             (feat "hefty hauler")
             (feat "quick jump")
             (feat "titan wrestler")
             (feat "underwater marauder")
             (feat "powerful leap")
             (feat "rapid mantel")
             (feat "quick climb")
             (feat "quick swim")
             (feat "wall jump")
             (feat "cloud jump")
             (feat "alchemical crafting")
             (feat "quick repair")
             (feat "snare crafting")
             (feat "specialty crafting")
             (feat "magical crafting")
             (feat "impeccable crafting")
             (feat "inventory")
             (feat "craft anything")
             (feat "charming liar")
             (feat "lengthy diversion")
             (feat "lie to me")
             (feat "confabulator")
             (feat "quick disguise")
             (feat "slippery secrets")
             (feat "bargain hunter")
             (feat "group impression")
             (feat "hobnobber")
             (feat "glad-hand")
             (feat "shameless request")
             (feat "legendary negotiation")
             (feat "group coercion")
             (feat "intimidating glare")
             (feat "quick coercion")
             (feat "intimidating prowess")
             (feat "lasting coercion")
             (feat "battle cry")
             (feat "terrified retreat")
             (feat "scare to death")
             (feat "additional lore")
             (feat "experienced professional")
             (feat "unmistakable lore")
             (feat "legendary professional")
             (feat "battle medicine")
             (feat "continual recovery")
             (feat "robust recovery")
             (feat "ward medic")
             (feat "legendary medic")
             (feat "natural medicine")
             (feat "train animal")
             (feat "bonded animal")
             (feat "oddity identification")
             (feat "bizarre magic")
             (feat "fascinating performance")
             (feat "impressive performance")
             (feat "virtuosic performer")
             (feat "legendary performer")
             (feat "student of the canon")
             (feat "divine guidance")
             (feat "courtly graces")
             (feat "multilingual")
             (feat "read lips")
             (feat "sign language")
             (feat "streetwise")
             (feat "connections")
             (feat "legendary codebreaker")
             (feat "legendary linguist")
             (feat "experience smuggler")
             (feat "terrain stalker")
             (feat "quiet allies")
             (feat "foil senses")
             (feat "swift sneak")
             (feat "legendary sneak")
             (feat "experienced tracker")
             (feat "forager")
             (feat "survey wildlife")
             (feat "terrain expertise")
             (feat "planar survival")
             (feat "legendary survivalist")
             (feat "pickpocket")
             (feat "subtle theft")
             (feat "wary disarmament")
             (feat "quick unlock")
             (feat "legendary thief")
             (feat "alchemical familiar" {:class "alchemist", :level 1})
             (feat "alchemical savant" {:class "alchemist", :level 1})
             (feat "calculated splash" {:class "alchemist", :level 4})
             (feat "combine elixirs" {:class "alchemist", :level 6})
             (feat "craft philosopher's stone" {:class "alchemist", :level 20})
             (feat "debilitating bomb" {:class "alchemist", :level 6})
             (feat "directional bombs" {:class "alchemist", :level 6})
             (feat "efficient alchemy" {:class "alchemist", :level 4})
             (feat "elastic mutagen" {:class "alchemist", :level 10})
             (feat "enduring alchemy" {:class "alchemist", :level 4})
             (feat "external elixir" {:class "alchemist", :level 16})
             (feat "expanded splash" {:class "alchemist", :level 10})
             (feat "exploitive bomb" {:class "alchemist", :level 16})
             (feat "extended elixir" {:class "alchemist", :level 12})
             (feat "far lobber" {:class "alchemist", :level 1})
             (feat "feral mutagen" {:class "alchemist", :level 8})
             (feat "glib mutagen" {:class "alchemist", :level 14})
             (feat "greater debilitating bomb" {:class "alchemist", :level 10})
             (feat "greater merciful elixir" {:class "alchemist", :level 14})
             (feat "improbable elixirs" {:class "alchemist", :level 18})
             (feat "invincible mutagen" {:class "alchemist", :level 12})
             (feat "mega bomb" {:class "alchemist", :level 20})
             (feat "merciful elixir" {:class "alchemist", :level 10})
             (feat "mindblank mutagen" {:class "alchemist", :level 18})
             (feat "miracle worker" {:class "alchemist", :level 18})
             (feat "perfect debilitation" {:class "alchemist", :level 18})
             (feat "perfect mutagen" {:class "alchemist", :level 20})
             (feat "persistent mutagen" {:class "alchemist", :level 16})
             (feat "poison resistance" {:class "alchemist", :level 2})
             (feat "potent poisoner" {:class "alchemist", :level 10})
             (feat "quick bomber" {:class "alchemist", :level 1})
             (feat "revivifying mutagen" {:class "alchemist", :level 2})
             (feat "smoke bomb" {:class "alchemist", :level 2})
             (feat "sticky bomb" {:class "alchemist", :level 8})
             (feat "true debilitating bomb" {:class "alchemist", :level 14})
             (feat "uncanny bombs" {:class "alchemist", :level 12})
             })

(def feat-type {

                 })

(def feat-theme{

                })

(def feats-decorated
  (-> feats
      (feat-decorate feat-type :feat-type)
      (feat-decorate feat-theme :theme)
      )
  )
