(in-ns 'net.edmacdonald.pathfinder.entities)

(entity-type skill)

(def skills #{(skill "acrobatics")
              (skill "arcana")
              (skill "athletics")
              (skill "crafting")
              (skill "deception")
              (skill "diplomacy")
              (skill "intimidation")
              (skill "lore")
              (skill "medicine")
              (skill "nature")
              (skill "occultism")
              (skill "performance")
              (skill "religion")
              (skill "society")
              (skill "stealth")
              (skill "survival")
              (skill "thievery")})
