(in-ns 'net.edmacdonald.pathfinder.entities)

(entity-type background)

(def backgrounds #{(background "acolyte")
                   (background "acrobat")
                   (background "animal whisperer")
                   (background "artisan")
                   (background "artist")
                   (background "barkeep")
                   (background "barrister")
                   (background "bounty hunter")
                   (background "charlatan")
                   (background "criminal")
                   (background "detective")
                   (background "emissary")
                   (background "entertainer")
                   (background "farmhand")
                   (background "field medic")
                   (background "fortune teller")
                   (background "gambler")
                   (background "gladiator")
                   (background "guard")
                   (background "herbalist")
                   (background "hermit")
                   (background "hunter")
                   (background "laborer")
                   (background "martial disciple")
                   (background "merchant")
                   (background "miner")
                   (background "noble")
                   (background "nomad")
                   (background "prisoner")
                   (background "sailor")
                   (background "scholar")
                   (background "scout")
                   (background "street_urchin")
                   (background "tinker")
                   (background "warrior")})
