(in-ns 'net.edmacdonald.pathfinder.entities)

(key-name-map condition)

(def conditions #{(condition "blinded")
                  (condition "broken")
                  (condition "clumsy")
                  (condition "concealed")
                  (condition "confused")
                  (condition "controlled")
                  (condition "dazzled")
                  (condition "deafened")
                  (condition "doomed")
                  (condition "drained")
                  (condition "dying")
                  (condition "encumbered")
                  (condition "enfeebled")
                  (condition "fascinated")
                  (condition "fatigued")
                  (condition "flat-footed")
                  (condition "fleeing")
                  (condition "friendly")
                  (condition "frightened")
                  (condition "grabbed")
                  (condition "helpful")
                  (condition "hidden")
                  (condition "hostile")
                  (condition "immobilized")
                  (condition "indifferent")
                  (condition "invisible")
                  (condition "observed")
                  (condition "paralyzed")
                  (condition "persistent damage")
                  (condition "petrified")
                  (condition "prone")
                  (condition "quickened")
                  (condition "restrained")
                  (condition "sickened")
                  (condition "slowed")
                  (condition "stunned")
                  (condition "stupefied")
                  (condition "unconscious")
                  (condition "undetected")
                  (condition "unfriendly")
                  (condition "unnoticed")
                  (condition "wounded")})
