(in-ns 'net.edmacdonald.pathfinder.entities)

(entity-type language)

(def languages #{(language "common")
                 (language "draconic")
                 (language "dwarven")
                 (language "elven")
                 (language "gnomish")
                 (language "goblin")
                 (language "halfling")
                 (language "jotun")
                 (language "orcish")
                 (language "sylvan")
                 (language "undercommon")
                 (language "abyssal")
                 (language "aklo")
                 (language "aquan")
                 (language "auran")
                 (language "celestial")
                 (language "gnoll")
                 (language "ignan")
                 (language "infernal")
                 (language "necril")
                 (language "shadowtongue")
                 (language "terran")
                 (language "druidic")})
